"""Frozen V1 schema, generated from reviewed SQLAlchemy models."""
from alembic import op
import sqlalchemy as sa
revision = "0001"
down_revision = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('subscribers', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hypothesis', sa.String(length=2000), nullable=False),
    sa.Column('expected_result', sa.JSON(), nullable=False),
    sa.Column('content_strategy', sa.String(length=1000), nullable=False),
    sa.Column('title_strategy', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_strategy', sa.String(length=1000), nullable=False),
    sa.Column('hook_strategy', sa.String(length=1000), nullable=False),
    sa.Column('audience', sa.String(length=1000), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('design', sa.String(length=32), nullable=False),
    sa.Column('control_video_id', sa.String(length=64), nullable=True),
    sa.Column('confounders', sa.String(length=2000), nullable=False),
    sa.Column('measurement', sa.JSON(), nullable=True),
    sa.Column('actual_result', sa.JSON(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('suspected_cause', sa.String(length=2000), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('next_hypothesis', sa.String(length=2000), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['control_video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_strategy_key'), 'decisions', ['strategy_key'], unique=False)
    op.create_index(op.f('ix_decisions_video_id'), 'decisions', ['video_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('hypothesis', sa.String(length=2000), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('arms', sa.JSON(), nullable=False),
    sa.Column('objective_weights', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('origin_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('origin_views', sa.BigInteger(), nullable=False),
    sa.Column('predicted_views', sa.Float(), nullable=False),
    sa.Column('lower_views', sa.Float(), nullable=False),
    sa.Column('upper_views', sa.Float(), nullable=False),
    sa.Column('p100k', sa.Float(), nullable=True),
    sa.Column('p1m', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('calibration_n', sa.Integer(), nullable=False),
    sa.Column('actual_views', sa.BigInteger(), nullable=True),
    sa.Column('actual_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('absolute_error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'origin_at', 'horizon_hours')
    )
    op.create_index(op.f('ix_forecasts_target_at'), 'forecasts', ['target_at'], unique=False)
    op.create_index(op.f('ix_forecasts_video_id'), 'forecasts', ['video_id'], unique=False)
    op.create_table('ingest_cursors',
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('through', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'kind')
    )
    op.create_table('reach_daily',
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('report_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'day')
    )
    op.create_table('reports',
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'kind', 'start', 'end')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'observed_at')
    )
    op.create_index(op.f('ix_snapshots_observed_at'), 'snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_snapshots_video_id'), 'snapshots', ['video_id'], unique=False)
    op.create_table('video_daily',
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('watch_minutes', sa.Float(), nullable=False),
    sa.Column('average_duration', sa.Float(), nullable=False),
    sa.Column('average_percentage', sa.Float(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('subscribers_lost', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'day')
    )
    op.create_table('memory_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suspected_cause', sa.String(length=2000), nullable=False),
    sa.Column('next_hypothesis', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_reviews_decision_id'), 'memory_reviews', ['decision_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_reviews_decision_id'), table_name='memory_reviews')
    op.drop_table('memory_reviews')
    op.drop_table('video_daily')
    op.drop_index(op.f('ix_snapshots_video_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_observed_at'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('reports')
    op.drop_table('reach_daily')
    op.drop_table('ingest_cursors')
    op.drop_index(op.f('ix_forecasts_video_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_target_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_decisions_video_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_strategy_key'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_table('sync_runs')
    op.drop_table('model_runs')
    op.drop_table('channels')
    # ### end Alembic commands ###
